name: morphocluster
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  # Conda packages
  - python=3.10
  - numpy=1.22
  - pandas
  - h5py=3.6
  - scikit-learn=1.0
  - scipy
  - pip
  - hdbscan
  - Pillow
  - pytorch
  - torchvision
  - hiredis
  - joblib==1.1.0 # See https://github.com/scikit-learn-contrib/hdbscan/issues/562

  - pip:
    # pip packages required to run MorphoCluster but not specified by setup.py
    - gunicorn
    - werkzeug < 2.1 #See https://github.com/morphocluster/morphocluster/issues/66
