version: '3'
services:
  app:
    build:
      context: . # Relative to project root
      dockerfile: .devcontainer/Dockerfile
    env_file:
      - .devcontainer/.env

    volumes:
      - .:/morphocluster
      - morphocluster-data:/data
      - ~/.gitconfig:/root/.gitconfig

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

    # Run service on the same network as the database container, allows "forwardPorts" in devcontainer.json function.
    network_mode: service:postgres
    # Uncomment the next line to use a non-root user for all processes.
    # user: mambauser
    # Use "forwardPorts" in **devcontainer.json** to forward an app port locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)
